### ISSUE TITLE
I got an error: Cannot use 'in' operator to search for 'issued' in undefined

### ISSUE THREAD

**Issue by nguyenvansutt** [fent/socket.io-clusterhub#8]
This is error: 
TypeError: Cannot use 'in' operator to search for 'issued' in undefined
    at Manager.garbageCollection (/usr/local/src/livechat/node_modules/socket.io/lib/manager.js:1023:21)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

It dont know when it raise. while using app, the app die, I check log and saw it.
my socket.io version: 0.9.16, mongodb 1.4.7, Iam using cluster and domain in nodejs

**Comment by fent** [comment]
this looks like an error with socket.io

**Comment by nguyenvansutt** [comment]
I dont think so, you can refer some links below:
https://github.com/Automattic/socket.io/pull/408
https://groups.google.com/forum/#!topic/socket_io/1i9awrdZ0CI
https://github.com/Automattic/socket.io/issues/2038
https://github.com/Automattic/socket.io/issues/1362
http://www.farennikov.com/2013/06/scaling-socket-io-with-node-js-cluster/#.VPkcSPmUddM

**Comment by fent** [comment]
that still doesn't show that the error is caused by this module. and you might not get much help from socket.io devs either since you're using an older version.
